/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import javax.swing.JOptionPane;

/**
 *
 * @author Jesus
 */
public class Interfaz2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz2
     */
    double v[];
    public Interfaz2() {
        initComponents();
        txtArea.setEditable(false);
        txtArea2.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtLongitud = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea2 = new javax.swing.JTextArea();
        jPanel5 = new javax.swing.JPanel();
        cmdCrear = new javax.swing.JButton();
        cmdLlenarManual = new javax.swing.JButton();
        cmdLlenarAutomatico = new javax.swing.JButton();
        cmdMostrar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();
        cmbCombo = new javax.swing.JComboBox<>();
        cmdCalcuar = new javax.swing.JButton();
        cmdPrimos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Dato inicial"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Longitud");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 27, -1, -1));

        txtLongitud.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLongitudKeyTyped(evt);
            }
        });
        jPanel4.add(txtLongitud, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 80, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 170, 60));

        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 24)); // NOI18N
        jLabel2.setText("Vectores");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 110, 30));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Elementos"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 220, 130));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Resultados"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArea2.setColumns(20);
        txtArea2.setRows(5);
        jScrollPane2.setViewportView(txtArea2);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 230, 140));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdCrear.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cmdCrear.setForeground(new java.awt.Color(0, 102, 0));
        cmdCrear.setText("Crear");
        cmdCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCrearActionPerformed(evt);
            }
        });
        jPanel5.add(cmdCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, -1));

        cmdLlenarManual.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cmdLlenarManual.setText("Llenar Manual");
        cmdLlenarManual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarManualActionPerformed(evt);
            }
        });
        jPanel5.add(cmdLlenarManual, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 140, -1));

        cmdLlenarAutomatico.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cmdLlenarAutomatico.setText("Llenar Automatico");
        cmdLlenarAutomatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLlenarAutomaticoActionPerformed(evt);
            }
        });
        jPanel5.add(cmdLlenarAutomatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 140, -1));

        cmdMostrar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cmdMostrar.setText("Mostrar");
        cmdMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdMostrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 140, -1));

        cmdBorrar.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 11)); // NOI18N
        cmdBorrar.setForeground(new java.awt.Color(102, 0, 0));
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 140, -1));

        cmbCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pares", "Impares", "" }));
        jPanel5.add(cmbCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        cmdCalcuar.setForeground(new java.awt.Color(0, 153, 0));
        cmdCalcuar.setText("Calcular");
        cmdCalcuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCalcuarActionPerformed(evt);
            }
        });
        jPanel5.add(cmdCalcuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, -1));

        cmdPrimos.setText("Primos");
        cmdPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrimosActionPerformed(evt);
            }
        });
        jPanel5.add(cmdPrimos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 140, -1));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 180, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLongitudKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLongitudKeyTyped
        char c=evt.getKeyChar();

        if(!Character.isDigit(evt.getKeyChar())){
            getToolkit().beep();

            evt.consume();

        }
    }//GEN-LAST:event_txtLongitudKeyTyped

    private void cmdCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCrearActionPerformed
        int longitud,opc,opercion=0;
        if (txtLongitud.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Digite la longitud","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
        }else if (Integer.parseInt(txtLongitud.getText().trim())==0){
            JOptionPane.showMessageDialog(this, " La longitud no puede ser 0","Error",JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
            txtLongitud.selectAll();
        }else {
            longitud =  Integer.parseInt(txtLongitud.getText());
            v = new double[longitud];

            JOptionPane.showMessageDialog(this, "Vector creado exitosamente");

        }
    }//GEN-LAST:event_cmdCrearActionPerformed

    private void cmdLlenarManualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarManualActionPerformed
        double n;
        for ( int i=0; i < v.length;i++){
            n= Double.parseDouble(JOptionPane.showInputDialog(this,"Digite el elemnto en la posicion "+i));
            v[i]=n;
        }
    }//GEN-LAST:event_cmdLlenarManualActionPerformed

    private void cmdLlenarAutomaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLlenarAutomaticoActionPerformed
        int n,ram;
        ram=Integer.parseInt(JOptionPane.showInputDialog(this,"Digite el valor maximo que puede tomar un elemento "));
        for ( int i=0; i < v.length;i++){
            n = (int)(Math.random()*ram + 1);;
            v[i]=n;
        }
    }//GEN-LAST:event_cmdLlenarAutomaticoActionPerformed

    private void cmdMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdMostrarActionPerformed

        for (int i = 0; i < v.length; i++) {
            txtArea.append(v [i]+"\n");

        }
    }//GEN-LAST:event_cmdMostrarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
        txtLongitud.setText("");
        txtArea.setText("");
        v = null;
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void cmdCalcuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCalcuarActionPerformed
         int opc=0,pares=0,resu=0,impares=0,res=0,primos=0;
        String res1;
        opc=cmbCombo.getSelectedIndex();
        if (txtLongitud.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la longitud del vector", "Error", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
        }else{
         for (int i = 0; i < v.length; i++) {
           
                switch (opc){
                    case 0:
                  
            if (v[i]%2==0) {
                pares++;
            }else{
                
            }
        resu=pares;
        break;
                    case 1: 
                        if (v[i]%2!=0) {
                impares++;
            }else{             
                        }
          resu=impares;
          break;
                    
            
                } res1=String.valueOf(resu);
                txtArea2.setText(res1);  
        
        }
        }
    }//GEN-LAST:event_cmdCalcuarActionPerformed

    private void cmdPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrimosActionPerformed
        if (txtLongitud.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite la longitud del vector", "Error", JOptionPane.ERROR_MESSAGE);
            txtLongitud.requestFocusInWindow();
        }else{
        int primos=0, res; 
     String resu;
        for (int i = 0; i < v.length; i++) {
           res=0; 
            for (int j = 1; j <= v[i]; j++) {
                if (v[i] % j == 0) {
                    res++;
                }
            }
            if (res == 2) {
                primos++;
            }
 
}
      
        resu=String.valueOf(primos);
        txtArea2.setText(resu);
        }
    }//GEN-LAST:event_cmdPrimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCombo;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdCalcuar;
    private javax.swing.JButton cmdCrear;
    private javax.swing.JButton cmdLlenarAutomatico;
    private javax.swing.JButton cmdLlenarManual;
    private javax.swing.JButton cmdMostrar;
    private javax.swing.JButton cmdPrimos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JTextArea txtArea2;
    private javax.swing.JTextField txtLongitud;
    // End of variables declaration//GEN-END:variables
}
